# Site settings
title: Matt James Media
email: mattjamesmedia@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A multimedia professional with expertise in interactive design and development, photography and copy writing
baseurl: "/blog/_site" # the subpath of your site, e.g. /blog/
url: "http://mattjamesmedia.com" # the base hostname & protocol for your site

twitter_username: mattFrankJames
github_username:  mattJamesMedia

# Build settings
markdown: kramdown

